#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

$SCRIPT_PATH/scripts/astyle-csharp --suffix=none --lineend=linux $(find . -name "*.cs" -or -name "*.template" | egrep -v '(ThirdParty|MonoGame.Framework|2MGFX)')
echo diff after astyle
git diff HEAD
$SCRIPT_PATH/scripts/corrent-empty-lines | grep -v "uninitialized value"
echo diff after corrent-empty-lines
git diff HEAD
